package requirements

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/runmedev/owl/internal/model"
	"github.com/runmedev/owl/internal/registry"
	"github.com/runmedev/owl/internal/store"
)

func TestContractsFromConfigInfersRequiredDotenvBindings(t *testing.T) {
	t.Parallel()

	contracts, err := ContractsFromConfig(model.ConfigInput{
		Needs: []model.NeedInput{
			{
				ID:       "redis.queues",
				Type:     model.TypeUniverseRedis,
				Instance: "queues",
			},
		},
	}, model.Source{Name: "owl.toml"}, registry.NewBuiltInRegistry())
	require.NoError(t, err)
	require.Len(t, contracts, 1)
	require.Len(t, contracts[0].Bindings, 3)

	byKey := bindingsByKey(contracts[0].Bindings)
	host := byKey["QUEUES_REDIS_HOST"]
	assert.Equal(t, model.FieldRef{TypeID: model.TypeUniverseRedis, Instance: "queues", Field: "host"}, host.FieldRef)
	assert.Equal(t, "Redis server hostname", host.Description)
	assert.True(t, host.Required)

	password := byKey["QUEUES_REDIS_PASSWORD"]
	assert.Equal(t, model.FieldRef{TypeID: model.TypeUniverseRedis, Instance: "queues", Field: "password"}, password.FieldRef)
	assert.Equal(t, "Redis password", password.Description)
	assert.True(t, password.Required)
}

func TestContractsFromConfigUsesPreferredKeysForDefaultInstance(t *testing.T) {
	t.Parallel()

	contracts, err := ContractsFromConfig(model.ConfigInput{
		Needs: []model.NeedInput{
			{
				ID:       "redis.default",
				Type:     model.TypeUniverseRedis,
				Instance: "default",
			},
		},
	}, model.Source{Name: "owl.toml"}, registry.NewBuiltInRegistry())
	require.NoError(t, err)

	byKey := bindingsByKey(contracts[0].Bindings)
	assert.Contains(t, byKey, "REDIS_HOST")
	assert.Contains(t, byKey, "REDIS_PORT")
	assert.Contains(t, byKey, "REDIS_PASSWORD")
}

func TestContractsFromConfigAppliesDotenvOverrides(t *testing.T) {
	t.Parallel()

	contracts, err := ContractsFromConfig(model.ConfigInput{
		Needs: []model.NeedInput{
			{
				ID:       "redis.queues",
				Type:     model.TypeUniverseRedis,
				Instance: "queues",
				Dotenv: &model.DotenvProjectionInput{
					Fields: []model.DotenvFieldBindingInput{
						{Field: "password", Key: "REDIS_AUTH_TOKEN"},
					},
				},
			},
		},
	}, model.Source{Name: "owl.toml"}, registry.NewBuiltInRegistry())
	require.NoError(t, err)

	byKey := bindingsByKey(contracts[0].Bindings)
	assert.Contains(t, byKey, "QUEUES_REDIS_HOST")
	assert.Contains(t, byKey, "QUEUES_REDIS_PORT")
	assert.Contains(t, byKey, "REDIS_AUTH_TOKEN")
	assert.NotContains(t, byKey, "QUEUES_REDIS_PASSWORD")
}

func TestContractsFromConfigRejectsUnknownFields(t *testing.T) {
	t.Parallel()

	_, err := ContractsFromConfig(model.ConfigInput{
		Needs: []model.NeedInput{
			{
				ID:       "redis.queues",
				Type:     model.TypeUniverseRedis,
				Instance: "queues",
				Dotenv: &model.DotenvProjectionInput{
					Fields: []model.DotenvFieldBindingInput{
						{Field: "username", Key: "REDIS_USERNAME"},
					},
				},
			},
		},
	}, model.Source{Name: "owl.toml"}, registry.NewBuiltInRegistry())
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unknown field")
}

func TestContractsFromConfigRejectsDuplicateDotenvKeys(t *testing.T) {
	t.Parallel()

	_, err := ContractsFromConfig(model.ConfigInput{
		Needs: []model.NeedInput{
			{
				ID:       "redis.queues",
				Type:     model.TypeUniverseRedis,
				Instance: "queues",
				Dotenv: &model.DotenvProjectionInput{
					Fields: []model.DotenvFieldBindingInput{
						{Field: "host", Key: "REDIS_DUPLICATE"},
						{Field: "port", Key: "REDIS_DUPLICATE"},
					},
				},
			},
		},
	}, model.Source{Name: "owl.toml"}, registry.NewBuiltInRegistry())
	require.Error(t, err)
	assert.Contains(t, err.Error(), "duplicate dotenv key")
}

func TestRenderDotenvSpec(t *testing.T) {
	t.Parallel()

	contracts, err := ContractsFromConfig(model.ConfigInput{
		Needs: []model.NeedInput{
			{
				ID:       "redis.queues",
				Type:     model.TypeUniverseRedis,
				Instance: "queues",
				Dotenv: &model.DotenvProjectionInput{
					Fields: []model.DotenvFieldBindingInput{
						{Field: "password", Key: "REDIS_AUTH_TOKEN"},
					},
				},
			},
		},
	}, model.Source{Name: "owl.toml"}, registry.NewBuiltInRegistry())
	require.NoError(t, err)

	rendered, err := RenderDotenvSpec(contracts, registry.NewBuiltInRegistry())
	require.NoError(t, err)

	assert.Equal(t, strings.Join([]string{
		"# Generated by Owl from Owl config. Do not edit by hand.",
		"",
		`QUEUES_REDIS_HOST="Redis server hostname" # Host!`,
		`QUEUES_REDIS_PORT="Redis server port"     # Port!`,
		`REDIS_AUTH_TOKEN="Redis password"         # Secret!`,
		"",
	}, "\n"), rendered)
}

func bindingsByKey(bindings []store.EnvBinding) map[string]store.EnvBinding {
	result := make(map[string]store.EnvBinding, len(bindings))
	for _, binding := range bindings {
		result[binding.Key] = binding
	}
	return result
}
