package requirements

import (
	"fmt"
	"sort"
	"strings"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"

	"github.com/runmedev/owl/internal/model"
	"github.com/runmedev/owl/internal/registry"
	"github.com/runmedev/owl/internal/store"
)

const GeneratedDotenvSpecHeader = "# Generated by Owl from owl.cue. Do not edit by hand."

func ParseCUEContracts(raw []byte, source model.Source, types registry.TypeProvider) ([]store.EnvContract, error) {
	if len(raw) == 0 {
		return nil, nil
	}
	if source.Name == "" {
		source = model.Source{Name: "owl.cue", Kind: "owl-cue"}
	}
	if source.Kind == "" {
		source.Kind = "owl-cue"
	}
	if types == nil {
		types = registry.NewBuiltInRegistry()
	}

	ctx := cuecontext.New()
	value := ctx.CompileBytes(raw)
	if err := value.Err(); err != nil {
		return nil, err
	}

	needs := value.LookupPath(cue.ParsePath("needs"))
	if !needs.Exists() {
		return nil, nil
	}

	var contracts []store.EnvContract
	kinds, err := needs.Fields()
	if err != nil {
		return nil, err
	}
	var order uint
	for kinds.Next() {
		instances, err := kinds.Value().Fields()
		if err != nil {
			return nil, fmt.Errorf("needs.%s: %w", kinds.Label(), err)
		}
		for instances.Next() {
			instanceName := instances.Label()
			instance := instances.Value()
			typeRef, err := cueString(instance, "type")
			if err != nil {
				return nil, fmt.Errorf("needs.%s.%s: %w", kinds.Label(), instanceName, err)
			}
			typeDef, ok, err := types.ResolveTypeRef(typeRef)
			if err != nil {
				return nil, fmt.Errorf("needs.%s.%s: %w", kinds.Label(), instanceName, err)
			}
			if !ok {
				return nil, fmt.Errorf("needs.%s.%s: unknown type %q", kinds.Label(), instanceName, typeRef)
			}
			env := instance.LookupPath(cue.ParsePath("env"))
			if !env.Exists() {
				return nil, fmt.Errorf("needs.%s.%s: env bindings are required", kinds.Label(), instanceName)
			}
			envFields, err := env.Fields()
			if err != nil {
				return nil, fmt.Errorf("needs.%s.%s.env: %w", kinds.Label(), instanceName, err)
			}
			contract := store.EnvContract{
				Source:     source,
				Projection: model.ProjectionDotenv,
			}
			for envFields.Next() {
				fieldName := envFields.Label()
				fieldDef, ok := typeDef.Fields[fieldName]
				if !ok {
					return nil, fmt.Errorf("needs.%s.%s.env.%s: unknown field for type %s", kinds.Label(), instanceName, fieldName, typeDef.ID)
				}
				key, err := envFields.Value().String()
				if err != nil {
					return nil, fmt.Errorf("needs.%s.%s.env.%s: %w", kinds.Label(), instanceName, fieldName, err)
				}
				order++
				contract.Bindings = append(contract.Bindings, store.EnvBinding{
					FieldRef: model.FieldRef{
						TypeID:   typeDef.ID,
						Instance: instanceName,
						Field:    fieldName,
					},
					Key:         key,
					Projection:  model.ProjectionDotenv,
					Required:    fieldDef.Required,
					Description: fieldDef.Description,
					Source:      source,
					Order:       order,
				})
			}
			contracts = append(contracts, contract)
		}
	}
	return contracts, nil
}

func RenderDotenvSpec(contracts []store.EnvContract, types registry.TypeProvider) (string, error) {
	if len(contracts) == 0 {
		return GeneratedDotenvSpecHeader + "\n", nil
	}
	if types == nil {
		types = registry.NewBuiltInRegistry()
	}

	var bindings []store.EnvBinding
	for _, contract := range contracts {
		bindings = append(bindings, contract.Bindings...)
	}
	sort.SliceStable(bindings, func(i, j int) bool {
		if bindings[i].Order != 0 && bindings[j].Order != 0 && bindings[i].Order != bindings[j].Order {
			return bindings[i].Order < bindings[j].Order
		}
		return bindings[i].Key < bindings[j].Key
	})

	var rendered []renderedBinding
	maxLeftWidth := 0
	for _, binding := range bindings {
		typeDef, ok := types.ResolveType(binding.FieldRef.TypeID)
		if !ok {
			return "", fmt.Errorf("unknown type %s", binding.FieldRef.TypeID)
		}
		fieldDef, ok := typeDef.Fields[binding.FieldRef.Field]
		if !ok {
			return "", fmt.Errorf("unknown field %s for type %s", binding.FieldRef.Field, binding.FieldRef.TypeID)
		}
		left := binding.Key + "=" + strconvQuote(binding.Description)
		if len(left) > maxLeftWidth {
			maxLeftWidth = len(left)
		}
		rendered = append(rendered, renderedBinding{
			left:     left,
			typeName: dotenvSpecName(fieldDef.TypeID),
			required: binding.Required,
		})
	}

	var b strings.Builder
	_, _ = b.WriteString(GeneratedDotenvSpecHeader)
	_, _ = b.WriteString("\n\n")
	for _, binding := range rendered {
		_, _ = b.WriteString(binding.left)
		_, _ = b.WriteString(strings.Repeat(" ", maxLeftWidth-len(binding.left)+1))
		_, _ = b.WriteString("# ")
		_, _ = b.WriteString(binding.typeName)
		if binding.required {
			_ = b.WriteByte('!')
		}
		_ = b.WriteByte('\n')
	}
	return b.String(), nil
}

type renderedBinding struct {
	left     string
	typeName string
	required bool
}

func cueString(value cue.Value, path string) (string, error) {
	result, err := value.LookupPath(cue.ParsePath(path)).String()
	if err != nil {
		return "", fmt.Errorf("%s: %w", path, err)
	}
	return result, nil
}

func dotenvSpecName(typeID model.TypeID) string {
	switch typeID {
	case model.TypeCoreSecret:
		return "Secret"
	case model.TypeCoreURL:
		return "Url"
	case model.TypeCoreHost:
		return "Host"
	case model.TypeCorePort:
		return "Port"
	case model.TypeCorePlain:
		return "Plain"
	default:
		return "Opaque"
	}
}

func strconvQuote(s string) string {
	return `"` + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `"`, `\"`) + `"`
}
