package requirements

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/runmedev/owl/internal/model"
	"github.com/runmedev/owl/internal/registry"
	"github.com/runmedev/owl/internal/store"
)

func TestParseCUEContracts(t *testing.T) {
	t.Parallel()

	contracts, err := ParseCUEContracts([]byte(`
package owl

needs: redis: queues: {
	type: "github.com/runmedev/owl/types/universe/redis"
	env: {
		host:     "REDIS_HOST"
		port:     "REDIS_PORT"
		password: "REDIS_PASSWORD"
	}
}
`), model.Source{Name: "owl.cue"}, registry.NewBuiltInRegistry())
	require.NoError(t, err)
	require.Len(t, contracts, 1)
	require.Len(t, contracts[0].Bindings, 3)

	byKey := bindingsByKey(contracts[0].Bindings)
	host := byKey["REDIS_HOST"]
	assert.Equal(t, model.FieldRef{TypeID: model.TypeUniverseRedis, Instance: "queues", Field: "host"}, host.FieldRef)
	assert.Equal(t, "Redis server hostname", host.Description)
	assert.True(t, host.Required)

	password := byKey["REDIS_PASSWORD"]
	assert.Equal(t, model.FieldRef{TypeID: model.TypeUniverseRedis, Instance: "queues", Field: "password"}, password.FieldRef)
	assert.Equal(t, "Redis password", password.Description)
	assert.True(t, password.Required)
}

func TestParseCUEContractsRejectsUnknownFields(t *testing.T) {
	t.Parallel()

	_, err := ParseCUEContracts([]byte(`
package owl

needs: redis: queues: {
	type: "github.com/runmedev/owl/types/universe/redis"
	env: username: "REDIS_USERNAME"
}
`), model.Source{Name: "owl.cue"}, registry.NewBuiltInRegistry())
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unknown field")
}

func TestRenderDotenvSpec(t *testing.T) {
	t.Parallel()

	contracts, err := ParseCUEContracts([]byte(`
package owl

needs: redis: queues: {
	type: "github.com/runmedev/owl/types/universe/redis"
	env: {
		host:     "REDIS_HOST"
		port:     "REDIS_PORT"
		password: "REDIS_PASSWORD"
	}
}
`), model.Source{Name: "owl.cue"}, registry.NewBuiltInRegistry())
	require.NoError(t, err)

	rendered, err := RenderDotenvSpec(contracts, registry.NewBuiltInRegistry())
	require.NoError(t, err)

	assert.Equal(t, strings.Join([]string{
		"# Generated by Owl from owl.cue. Do not edit by hand.",
		"",
		`REDIS_HOST="Redis server hostname" # Host!`,
		`REDIS_PORT="Redis server port"     # Port!`,
		`REDIS_PASSWORD="Redis password"    # Secret!`,
		"",
	}, "\n"), rendered)
}

func bindingsByKey(bindings []store.EnvBinding) map[string]store.EnvBinding {
	result := make(map[string]store.EnvBinding, len(bindings))
	for _, binding := range bindings {
		result[binding.Key] = binding
	}
	return result
}
