package requirements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/runmedev/owl/internal/model"
	"github.com/runmedev/owl/internal/registry"
	"github.com/runmedev/owl/internal/store"
)

const GeneratedDotenvSpecHeaderPrefix = "# Generated by Owl from "

const GeneratedDotenvSpecHeader = GeneratedDotenvSpecHeaderPrefix + "Owl config. Do not edit by hand."

func RenderDotenvSpec(contracts []store.EnvContract, types registry.TypeProvider) (string, error) {
	if len(contracts) == 0 {
		return GeneratedDotenvSpecHeader + "\n", nil
	}
	if types == nil {
		types = registry.NewBuiltInRegistry()
	}

	var bindings []store.EnvBinding
	for _, contract := range contracts {
		bindings = append(bindings, contract.Bindings...)
	}
	sort.SliceStable(bindings, func(i, j int) bool {
		if bindings[i].Order != 0 && bindings[j].Order != 0 && bindings[i].Order != bindings[j].Order {
			return bindings[i].Order < bindings[j].Order
		}
		return bindings[i].Key < bindings[j].Key
	})

	var rendered []renderedBinding
	maxLeftWidth := 0
	for _, binding := range bindings {
		typeDef, ok := types.ResolveType(binding.FieldRef.TypeID)
		if !ok {
			return "", fmt.Errorf("unknown type %s", binding.FieldRef.TypeID)
		}
		fieldDef, ok := typeDef.Fields[binding.FieldRef.Field]
		if !ok {
			return "", fmt.Errorf("unknown field %s for type %s", binding.FieldRef.Field, binding.FieldRef.TypeID)
		}
		left := binding.Key + "=" + strconvQuote(binding.Description)
		if len(left) > maxLeftWidth {
			maxLeftWidth = len(left)
		}
		rendered = append(rendered, renderedBinding{
			left:     left,
			typeName: dotenvSpecName(fieldDef.TypeID),
			required: binding.Required,
		})
	}

	var b strings.Builder
	_, _ = b.WriteString(generatedDotenvSpecHeader(contracts))
	_, _ = b.WriteString("\n\n")
	for _, binding := range rendered {
		_, _ = b.WriteString(binding.left)
		_, _ = b.WriteString(strings.Repeat(" ", maxLeftWidth-len(binding.left)+1))
		_, _ = b.WriteString("# ")
		_, _ = b.WriteString(binding.typeName)
		if binding.required {
			_ = b.WriteByte('!')
		}
		_ = b.WriteByte('\n')
	}
	return b.String(), nil
}

func generatedDotenvSpecHeader(contracts []store.EnvContract) string {
	source := "Owl config"
	if len(contracts) > 0 {
		name := strings.TrimSpace(contracts[0].Source.Name)
		if name != "" && name != "[config]" {
			source = name
		}
	}
	return GeneratedDotenvSpecHeaderPrefix + source + ". Do not edit by hand."
}

type renderedBinding struct {
	left     string
	typeName string
	required bool
}

func dotenvSpecName(typeID model.TypeID) string {
	switch typeID {
	case model.TypeCoreSecret:
		return "Secret"
	case model.TypeCoreURL:
		return "Url"
	case model.TypeCorePlain:
		return "Plain"
	default:
		return "Opaque"
	}
}

func strconvQuote(s string) string {
	return `"` + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `"`, `\"`) + `"`
}
