[needs.openai.default]
type = "github.com/runmedev/owl/types/universe/openai"

[needs.openai.proxy]
type = "github.com/runmedev/owl/types/universe/openai"

[needs.openai.proxy.dotenv]
apiKey = "PROXY_OPENAI_API_KEY"
baseURL = "PROXY_OPENAI_BASE_URL"
organization = "PROXY_OPENAI_ORG_ID"
project = "PROXY_OPENAI_PROJECT_ID"
