package cmd

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/runmedev/owl/pkg/owl"
)

func TestProjectSpecRendersGeneratedSpec(t *testing.T) {
	t.Parallel()

	client := &fakeStoreClient{
		projectResult: &ProjectSpecResult{Rendered: "REDIS_HOST=\"Redis server hostname\" # Plain!\n"},
	}
	cmd := newProjectCommand(StoreCommandOptions{
		ClientFactory: func(*cobra.Command) (StoreClient, error) {
			return client, nil
		},
	})

	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"spec", "--config", "owl.toml"})

	require.NoError(t, cmd.Execute())
	assert.True(t, client.projectCalled)
	assert.Equal(t, "owl.toml", client.projectReq.ConfigPath)
	assert.Equal(t, "REDIS_HOST=\"Redis server hostname\" # Plain!\n", out.String())
}

func TestProjectSpecOutputDashRendersGeneratedSpec(t *testing.T) {
	t.Parallel()

	client := &fakeStoreClient{
		projectResult: &ProjectSpecResult{Rendered: "REDIS_HOST=\"Redis server hostname\" # Plain!\n"},
	}
	cmd := newProjectCommand(StoreCommandOptions{
		ClientFactory: func(*cobra.Command) (StoreClient, error) {
			return client, nil
		},
	})

	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"spec", "--output", "-"})

	require.NoError(t, cmd.Execute())
	assert.Equal(t, "-", client.projectReq.Output)
	assert.Equal(t, "REDIS_HOST=\"Redis server hostname\" # Plain!\n", out.String())
}

func TestProjectSpecWriteDoesNotRender(t *testing.T) {
	t.Parallel()

	client := &fakeStoreClient{
		projectResult: &ProjectSpecResult{Rendered: "REDIS_HOST=\"Redis server hostname\" # Plain!\n"},
	}
	cmd := newProjectCommand(StoreCommandOptions{
		ClientFactory: func(*cobra.Command) (StoreClient, error) {
			return client, nil
		},
	})

	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"spec", "--write"})

	require.NoError(t, cmd.Execute())
	assert.True(t, client.projectReq.Write)
	assert.Empty(t, out.String())
}

func TestProjectSpecRejectsWriteAndOutput(t *testing.T) {
	t.Parallel()

	cmd := newProjectCommand(StoreCommandOptions{
		ClientFactory: func(*cobra.Command) (StoreClient, error) {
			return &fakeStoreClient{}, nil
		},
	})
	cmd.SetArgs([]string{"spec", "--write", "--output", ".env.spec"})

	err := cmd.Execute()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "use either --write or --output")
}

func TestLocalStoreClientProjectSpecLoadsTomlConfig(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	configPath := filepath.Join(dir, "owl.toml")
	require.NoError(t, os.WriteFile(configPath, []byte(`
[needs.redis.queues]
type = "github.com/runmedev/owl/types/universe/redis"

[needs.redis.queues.dotenv]
password = "REDIS_AUTH_TOKEN"
`), 0o600))

	client := NewLocalStoreClient(LocalStoreOptions{})
	result, err := client.ProjectSpec(context.Background(), ProjectSpecRequest{ConfigPath: configPath})
	require.NoError(t, err)

	assert.Equal(t, strings.Join([]string{
		"# Generated by Owl from " + configPath + ". Do not edit by hand.",
		"",
		`QUEUES_REDIS_HOST="Redis server hostname" # Plain!`,
		`QUEUES_REDIS_PORT="Redis server port"     # Plain!`,
		`REDIS_AUTH_TOKEN="Redis password"         # Secret!`,
		"",
	}, "\n"), result.Rendered)
}

func TestReadConfigFileSupportsJSONAndYAML(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	jsonPath := filepath.Join(dir, "owl.json")
	yamlPath := filepath.Join(dir, "owl.yaml")
	require.NoError(t, os.WriteFile(jsonPath, []byte(`{
  "needs": [
    {
      "id": "redis.default",
      "type": "github.com/runmedev/owl/types/universe/redis",
      "instance": "default"
    }
  ]
}`), 0o600))
	require.NoError(t, os.WriteFile(yamlPath, []byte(`
needs:
  - id: redis.default
    type: github.com/runmedev/owl/types/universe/redis
    instance: default
`), 0o600))

	jsonConfig, err := owl.ReadConfigFile(jsonPath)
	require.NoError(t, err)
	yamlConfig, err := owl.ReadConfigFile(yamlPath)
	require.NoError(t, err)

	require.Len(t, jsonConfig.Needs, 1)
	require.Len(t, yamlConfig.Needs, 1)
	assert.Equal(t, jsonConfig.Needs[0], yamlConfig.Needs[0])
}

func TestLocalStoreClientProjectSpecWriteRefusesHumanSpec(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	configPath := filepath.Join(dir, "owl.toml")
	specPath := filepath.Join(dir, ".env.spec")
	require.NoError(t, os.WriteFile(configPath, []byte(`
[needs.redis.default]
type = "github.com/runmedev/owl/types/universe/redis"
`), 0o600))
	require.NoError(t, os.WriteFile(specPath, []byte(`REDIS_HOST="Redis host" # Plain!`), 0o600))

	client := NewLocalStoreClient(LocalStoreOptions{})
	_, err := client.ProjectSpec(context.Background(), ProjectSpecRequest{ConfigPath: configPath, Output: specPath})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not Owl-generated")
}

func TestLocalStoreClientProjectSpecWriteOverwritesGeneratedSpec(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	configPath := filepath.Join(dir, "owl.toml")
	specPath := filepath.Join(dir, ".env.spec")
	require.NoError(t, os.WriteFile(configPath, []byte(`
[needs.redis.default]
type = "github.com/runmedev/owl/types/universe/redis"
`), 0o600))
	require.NoError(t, os.WriteFile(specPath, []byte("# Generated by Owl from Owl config. Do not edit by hand.\n"), 0o600))

	client := NewLocalStoreClient(LocalStoreOptions{})
	_, err := client.ProjectSpec(context.Background(), ProjectSpecRequest{ConfigPath: configPath, Output: specPath})
	require.NoError(t, err)

	raw, err := os.ReadFile(specPath)
	require.NoError(t, err)
	assert.Contains(t, string(raw), `REDIS_HOST="Redis server hostname"`)
}

func TestLocalStoreClientErrorsWhenConfigAndHumanSpecAreAutoDiscovered(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, "owl.toml"), []byte(`
[needs.redis.default]
type = "github.com/runmedev/owl/types/universe/redis"
`), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".env.spec"), []byte(`REDIS_HOST="Redis host" # Plain!`), 0o600))

	originalWd, err := os.Getwd()
	require.NoError(t, err)
	require.NoError(t, os.Chdir(dir))
	t.Cleanup(func() {
		require.NoError(t, os.Chdir(originalWd))
	})

	client := NewLocalStoreClient(LocalStoreOptions{})
	_, err = client.Check(context.Background(), CheckRequest{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "dotenv spec file exists beside Owl config")
}
